// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zCbvRgJ3r_rvFrmitUuSgrsczQf-uqA',
    appId: '1:396099734441:web:fced7e95284db1c01892b8',
    messagingSenderId: '396099734441',
    projectId: 'confab-dx2',
    authDomain: 'confab-dx2.firebaseapp.com',
    storageBucket: 'confab-dx2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmkIv-oYet57RdElsXSnIyErdfMZzFXZM',
    appId: '1:396099734441:android:d376ac91276e4c811892b8',
    messagingSenderId: '396099734441',
    projectId: 'confab-dx2',
    storageBucket: 'confab-dx2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIcBZOxx-K2wgvClTktlQs-I_dBaeAw0',
    appId: '1:396099734441:ios:f1b589632ef4df461892b8',
    messagingSenderId: '396099734441',
    projectId: 'confab-dx2',
    storageBucket: 'confab-dx2.appspot.com',
    iosClientId: '396099734441-nfbn76m9in7gigtvesmc6rliqgtcskin.apps.googleusercontent.com',
    iosBundleId: 'com.confab.confab',
  );
}
